### ISSUE TITLE
Different techniques of distance measurement

### ISSUE THREAD

**Issue by affiqazrin** [JustGlowing/minisom#65]
Propose a Hamming distance technique to calculate binary values including example of application.

**Comment by JustGlowing** [comment]
hi there, can you articulate your idea a bit more?

**Comment by affiqazrin** [comment]
hi. does Minisom support binary dataset for clustering? instead of using Euclidean distance technique to measure distance between nodes, can you provide a different approach of distance measurement by using Hamming technique?

**Comment by JustGlowing** [comment]
Only the euclidean distance is supported for the moment.

**Comment by niksart** [comment]
Hello all,
I've just implemented an alternative distance metric: Pearson's distance. If you think it's useful I could do a pull request.

**Comment by JustGlowing** [comment]
Hi Nicola, I'd like to have a look at your implementation. Before raising a
PR, just show me your repo.

**Comment by niksart** [comment]
@JustGlowing here's the compare changes on my branch "distance_metrics": [https://github.com/JustGlowing/minisom/compare/master...niksart:distance_metrics](https://github.com/JustGlowing/minisom/compare/master...niksart:distance_metrics)

**Comment by JustGlowing** [comment]
@niksart It does look like an interesting approach, still it affects only the computation of the errors (which are not used in training). You can raise a pull request if you want but before merging I would require some scientific justification (eg. papers that mention the usage of this distance) and quite a lot changes to the code.

**Comment by niksart** [comment]
@JustGlowing I thought that a change to  the `_distance_from_weights` function could also affect training (so that data points that have similar correlation will be linked to near som units). So... I think I should have looked more carefully at the code. So, can you please give me some hints and advice on how to do it? Any help would be greatly appreciated.

Now, I'll briefly explain you the reason I'm doing this. I'm working with some fMRI time series of voxel activations: thus, the data on which I would apply MiniSom is a matrix whose shape is `n_voxels x len_time_series`. And basically, as said before, I want that 2 voxels that have similar activation over time (i.e. high correlation of their time series) will be plotted nearly by the som. For doing this I can't use the euclidean distance, and I need the Pearson's distance (`1 - pearson_correlation(x,y)`).

Regarding the scientific justification: the Pearson distance is used in clustering (see [https://www.camo.com/resources/clustering.html](https://www.camo.com/resources/clustering.html) for a list of distance metrics even though _this is not a scientific justification_). If I will find studies in which they use som with Pearson distance I will let you know.

**Comment by JustGlowing** [comment]
There are two lines you should look at, this one where the activations are computed:

https://github.com/JustGlowing/minisom/blob/master/minisom.py#L187

and this one where the weights are updated:

https://github.com/JustGlowing/minisom/blob/master/minisom.py#L264

(it might be simple for you to look at how it was implemented in the past without using Einstein summation: https://github.com/JustGlowing/minisom/blob/be3aadce41e82503856cf2ef20418d019eded88f/minisom.py#L229)

If you plug your distance function here, you've done most of the job.

**Comment by niksart** [comment]
Thank you. I will comment again here when I will have implemented something.

**Comment by niksart** [comment]
https://github.com/JustGlowing/minisom/compare/master...niksart:distance_metrics

**Comment by niksart** [comment]
@JustGlowing In [https://github.com/JustGlowing/minisom/compare/master...niksart:distance_metrics](https://github.com/JustGlowing/minisom/compare/master...niksart:distance_metrics) I have changed the implementation of the calculation of the activation map depending on the distance metric. However, I don't think that a change to the update function is necessary. Why do you think it is?

Here is a paper that uses SOM with a correlation distance: [https://www.frontiersin.org/articles/10.3389/fnhum.2015.00400/full](https://www.frontiersin.org/articles/10.3389/fnhum.2015.00400/full). In particular, this part is the interesting one and contains many useful links:

_In this study, SOM adopts a correlation distance metric between the input vector and weight vectors to spot the winning neuron (Chuang et al., 1999; Ngan and Hu, 1999; Ngan et al., 2002; Peltier et al., 2003; Hausfeld et al., 2014), which is different from previous strategy that utilizes the Euclidean distance (Kohonen, 1982, 1990, 1995; Chuang et al., 1999; Haykin, 1999; Ngan and Hu, 1999; Ngan et al., 2002; Peltier et al., 2003; Hausfeld et al., 2014). When SOM is implemented, each generated exemplar will have one corresponding time course. Then further operations can be performed to find the correlation coefficient (CC) between the time course of each voxel of brain slices and the time courses of all exemplars. The biggest CC will occur when the voxel and its corresponding exemplar are of the same cluster._

**Comment by JustGlowing** [comment]
good morning @niksart,

Having a look at that paper I agree that you don't need to change the update function.

Do you still need to change `_distance_from_weights`? That one affects the way the errors are computed, which are based on the euclidean distance by definition.

**Comment by niksart** [comment]
I think that also for calculating the errors is better to use the correlation distance. This because, considering the weights of a unit, at the end of the training they will be a prototype of a time series. So, when you have to compute the distance between a time series and a prototype I don't think the Euclidean Distance would be useful. What do you think?

**Comment by JustGlowing** [comment]
I think I now understand more about your problem. If the data is properly scaled the euclidean distance will work anyways (also for training). Have a look at this example:

https://github.com/JustGlowing/minisom/blob/master/examples/TimeSeries.ipynb

It's on time series data, just all the values have been scaled in the same range. Usually you scale the data by removing the mean and dividing by the standard deviation on each column of your dataset.

**Comment by niksart** [comment]
Yes, you are right. And here's evidence for this: [https://arxiv.org/pdf/1601.02213.pdf](https://arxiv.org/pdf/1601.02213.pdf)

I'll use z-scores with Euclidean Distance. Thank you for the help.

**Comment by JustGlowing** [comment]
Glad I could help. Let me know how it goes.

Buona fortuna ;)

**Comment by JustGlowing** [comment]
Inspired by this discussion I decided to add a parameter to set the distance function to use for the activation of the map. You can check out the master branch.

I also implemented the cosine distance, which is equivalent to the pearson distance when the data is centered.

**Comment by niksart** [comment]
Thank you. This is good also for possible future distance metrics implementations
