### ISSUE TITLE
How can we make u-matrix with interstitial cells?

### ISSUE THREAD

**Issue by hnysidhu** [JustGlowing/minisom#78]
U-Matrix representation generally includes interstitial cells (hexagonal topology). For example, a SOM of 6 by 4 size has 11 by 7 nodes in the U-matrix representation. How can we achieve that using minisom?

**Comment by JustGlowing** [comment]
Hi there, I'm afraid that I don't understand what you are trying to achieve.

You can compute the U-Matrix using the method `distance_map` which returns a matrix with the same shape of the som.

**Comment by hnysidhu** [comment]
I would like to represent the distance between any two nodes on SOM by showing another node in between them, which would be coloured based on this distance. 
Something like this MATLAB implementation: [https://in.mathworks.com/help/deeplearning/ug/selforg_neighbor_dist.gif](url).

**Comment by JustGlowing** [comment]
I see, to achieve that you have to modify the following function to save the distances between neurons rather than averaging them:

https://github.com/JustGlowing/minisom/blob/master/minisom.py#L437

For making the visualization you can modify code from this example:

https://github.com/JustGlowing/minisom/blob/master/examples/HexagonalTopology.ipynb

**Comment by hnysidhu** [comment]
Alright, thanks.
